project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  search: true
  back-to-top-navigation: true
  reader-mode: true
  
  navbar:
    background: info
    left:
      - text: "主页"
        href: index.qmd
      - text: "预测性模型"
        href: predictive_models.qmd
      - text: "描述性模型"
        href: descriptive_models.qmd
      - text: "推断性模型"
        href: inferential_models.qmd



  sidebar:
    - title: "预测性模型"
      style: "docked"
      background: "#ffd9e6"
      foreground: "#1919e6"
      border: true
      alignment: left
      collapse-level: 4
      contents:
        - predictive_models.qmd

        - section: machine_learning.qmd
          contents: 
            - imputation.qmd
            - data_spilt.qmd
            - model_selection.qmd
            - feature_engineering.qmd
            - predict_performance.qmd
            - resample.qmd
            - cross_validation.qmd
            # - tune_hyperparameters.qmd
        - section: "Lazy Learning"
          contents:
            - kNN.qmd

        - section: "Supervised Learning"
          contents:
            - Regression.qmd
            - Classification.qmd
            - tree-based_models.qmd
            - survival.qmd
            
        - section: "Unsupervised Learning"
          contents:
            - Clustering.qmd
            - LDA.qmd
            - PCA.qmd
            - t-SNE.qmd
            - UMAP.qmd
            
        - section: "集成学习（Ensemble Learning）"
#         集成学习通过组合多个基学习器提高模型性能。主要包括以下几类：
# 
# 袋装法（Bagging）：如随机森林，通过训练多个样本子集的模型进行预测。
# 提升法（Boosting）：如梯度提升决策树（GBDT），通过逐步改进模型进行预测。
# 堆叠法（Stacking）：通过组合多个基础模型的输出进行预测。
# Gradient boosting
    - title: "描述性模型"
      contents: 
        - descriptive_models.qmd

    - title: "推断性模型"
      contents:
        - inferential_models.qmd





knitr: 
  opts_chunk: 
    comment: "#>"
    collapse: TRUE

execute:
  cache: true
  message: false
  warning: true

toc-depth: 4
number-sections: true
number-depth: 4
code-fold: show
code-link: true
code-tools: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-format: svg

editor: visual


