project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  search: true
  back-to-top-navigation: true
  reader-mode: true
  
  navbar:
    background: info
    left:
      - text: "主页"
        href: index.qmd
      - text: "预测性模型"
        href: predictive_models.qmd
      - text: "描述性模型"
        href: descriptive_models.qmd
      - text: "推断性模型"
        href: inferential_models.qmd



  sidebar:
    - title: "预测性模型"
      style: "docked"
      background: "#ffd9e6"
      foreground: "#1919e6"
      border: true
      alignment: left
      collapse-level: 4
      contents:
        - predictive_models.qmd
        - machine_learning.qmd
        - cross_validation.qmd

        - section: "Supervised Models"
          contents:
            - Regression.qmd
            - Classification.qmd
            - tree-based_models.qmd
            - survival.qmd
            
        - section: "Unsupervised Models"
          contents:
            - Clustering.qmd
            - PCA.qmd
            - t-SNE.qmd
            - UMAP.qmd
        
    - title: "描述模型"
      contents: 
        - descriptive_models.qmd

    - title: "推断模型"
      contents:
        - inferential_models.qmd





knitr: 
  opts_chunk: 
    comment: "#>"
    collapse: TRUE

execute:
  cache: true
  message: false
  warning: true

toc-depth: 4
number-sections: true
number-depth: 4
code-fold: show
code-link: true
code-tools: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-format: svg

editor: visual


