# 数据拆分


## 探索性数据分析

```{r}
library(tidymodels)
data(ames,package = "modeldata")

# 右偏
moments::skewness(ames$Sale_Price)
moments::agostino.test(ames$Sale_Price)
ggplot(ames, aes(x = Sale_Price)) + 
  geom_histogram(bins = 50, col= "white")


# 常用对数变换
ames <- ames |>mutate(Sale_Price = log10(Sale_Price))

# 近似正态
moments::skewness(ames$Sale_Price)
moments::agostino.test(ames$Sale_Price)
ggplot(ames, aes(x = Sale_Price)) + 
  geom_histogram(bins = 50, col= "white")+
    geom_vline(xintercept =quantile(ames$Sale_Price),lty=5 )


```

## 数据拆分 `rsample`

一般来说，拆分为训练集和测试集即可。

### 简单抽样

```{r}
set.seed(10)
ames_split <- initial_split(ames, prop = c(0.8))
ames_split

ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
dim(ames_train)
```

### 分层抽样

```{r}
set.seed(100)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_split

ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
dim(ames_train)
```

### 验证集

如果需要提前验证，可拆分为训练集、验证集和测试集

```{r}
set.seed(101)

# To put 60% into training, 20% in validation, and remaining 20% in testing:
ames_split3 <- initial_validation_split(ames, prop = c(0.6, 0.2),
                                       strata = Sale_Price)
ames_split3

ames_train3 <- training(ames_split3)
ames_test3 <- testing(ames_split3)
ames_valid3 <- validation(ames_split3)
```
